
//prueba api para buscar ppsible amigos
GET http://localhost:3001/noamigos/calamardo69@mail.com
//prueba api para traer todos los feedbacks
#####
GET http://localhost:3001/getfeedback/jantonios44@hotmail.com
//prueba api para traer todos los amigos
####
GET http://localhost:3001/amigos/patricio69@gmail.com
####
GET http://localhost:3001/publications/jantonios44@hotmail.com
###
GET http://localhost:3001/publicationsall
