//theme
const LIGHT_THEME="LIGHT_THEME"
const DARK_THEME="DARK_THEME"

export {LIGHT_THEME, DARK_THEME}

//login
const USER_LOGIN = "USER_LOGIN"
const USER_UNLOGIN = "USER_UNLOGIN"
const USER_LOGIN_SUCCEED = "USER_LOGIN_SUCCEED"
const USER_LOGIN_ERROR = "USER_LOGIN_ERROR"

export {USER_LOGIN, USER_UNLOGIN, USER_LOGIN_SUCCEED, USER_LOGIN_ERROR}

