//tema
const LIGHT_THEME="LIGHT_THEME"
const DARK_THEME="DARK_THEME"

export {LIGHT_THEME,DARK_THEME }

//CURSOS
const SAVE_CUORSE="SAVE_CUORSE"

const SAVED_CUORSE="SAVED_CUORSE"
const SAVED_CUORSE_ERROR="SAVED_CUORSE_ERROR"

export {SAVE_CUORSE,SAVED_CUORSE,SAVED_CUORSE_ERROR }

//friend request

const REQUEST_SEND="REQUEST_SEND"
const REQUEST_SENT="REQUEST_SENT"
const REQUEST_SENT_ERROR="REQUEST_SEND_ERROR"
export {REQUEST_SEND,REQUEST_SENT,REQUEST_SENT_ERROR}
