//theme
const LIGHT_THEME="LIGHT_THEME"
const DARK_THEME="DARK_THEME"

export {LIGHT_THEME, DARK_THEME}

//login
const USER_LOGIN = "USER_LOGIN"
const USER_UNLOGIN = "USER_UNLOGIN"
const USER_LOGIN_SUCCEED = "USER_LOGIN_SUCCEED"
const USER_LOGIN_ERROR = "USER_LOGIN_ERROR"
const USER_SAVE_DATA = "USER_SAVE_DATA"

export {USER_LOGIN, USER_UNLOGIN, USER_LOGIN_SUCCEED, USER_LOGIN_ERROR,USER_SAVE_DATA}


//CURSOS
const SAVE_CUORSE="SAVE_CUORSE"
const SAVED_CUORSE="SAVED_CUORSE"
const SAVED_CUORSE_ERROR="SAVED_CUORSE_ERROR"

export {SAVE_CUORSE,SAVED_CUORSE,SAVED_CUORSE_ERROR }

//friend request
const REQUEST_CANCEL="REQUEST_CANCEL"
const REQUEST_SEND="REQUEST_SEND"
const REQUEST_SENT="REQUEST_SENT"
const REQUEST_SENT_ERROR="REQUEST_SEND_ERROR"
export {REQUEST_CANCEL,REQUEST_SEND,REQUEST_SENT,REQUEST_SENT_ERROR}

//HABILIDADES
const SET_LOADING="SET_LOADING"
const SAVE_ABILITI="SAVE_ABILITI"
const SAVED_ABILITI="SAVED_ABILITI"
const SAVED_ABILITI_ERROR="SAVED_ABILITI_ERROR"

export {SET_LOADING,SAVE_ABILITI,SAVED_ABILITI,SAVED_ABILITI_ERROR}

//Ayuda

const SAVE_HELP="SAVE_HELP"
const SAVED_HELP="SAVED_HELP"
const SAVED_HELP_ERROR="SAVED_HELP_ERROR"

export {SAVE_HELP,SAVED_HELP,SAVED_HELP_ERROR}



//mostrar cursos

const GET_COURSE ="GET_COURSE"
const GOT_COURSE=" GOT_COURSE"
const GOT_COURSE_ERROR="GOT_COURSE_ERROR"

export { GET_COURSE,GOT_COURSE,GOT_COURSE_ERROR}

//mostrar habilidades

const GET_ABILITI ="GET_ABILITI"
const GOT_ABILITI=" GOT_ABILITI"
const GOT_ABILITI_ERROR="GOT_ABILITI_ERROR"

export { GET_ABILITI,GOT_ABILITI,GOT_ABILITI_ERROR}



//notificaciones

const GET_NOTIFICATIONS ="GET_NOTIFICATIONS"
const GOT_NOTIFICATIONS=" GOT_NOTIFICATIONS"
const GOT_NOTIFICATIONS_ERROR=" GOT_NOTIFICATIONS_ERROR"

export { GET_NOTIFICATIONS,GOT_NOTIFICATIONS, GOT_NOTIFICATIONS_ERROR}


